import { ReactComponent as Calendar } from "./calendar.svg";
import { ReactComponent as Chrome } from "./chrome.svg";
import { ReactComponent as Copy } from "./copy.svg";
import { ReactComponent as Desktop } from "./desktop.svg";
import { ReactComponent as Firefox } from "./firefox.svg";
import { ReactComponent as Mobile } from "./mobile.svg";
import { ReactComponent as Referrer } from "./referrer.svg";
import { ReactComponent as Safari } from "./safari.svg";
import { ReactComponent as Tablet } from "./tablet.svg";
import { ReactComponent as User } from "./user.svg";
export { Calendar, Chrome, Copy, Desktop, Firefox, Mobile, Referrer, Safari, Tablet, User, };
