import { invert } from "lodash";

const countriesShort = {
	AW: "Aruba",
	AF: "Afghanistan",
	AO: "Angola",
	AI: "Anguilla",
	AX: "Åland",
	AL: "Albania",
	AD: "Andorra",
	AE: "United Arab Emirates",
	AR: "Argentina",
	AM: "Armenia",
	AS: "American Samoa",
	AQ: "Antarctica",
	TF: "Territory of the French Southern and Antarctic Lands",
	AG: "Antigua and Barbuda",
	AU: "Australia",
	AT: "Austria",
	AZ: "Azerbaijan",
	BI: "Burundi",
	BE: "Belgium",
	BJ: "Benin",
	BF: "Burkina Faso",
	BD: "Bangladesh",
	BG: "Bulgaria",
	BH: "Bahrain",
	BS: "Bahamas",
	BA: "Bosnia and Herzegovina",
	BL: "Saint Barthélemy",
	SH: "Saint Helena, Ascension and Tristan da Cunha",
	BY: "Belarus",
	BZ: "Belize",
	BM: "Bermuda",
	BO: "Bolivia",
	BQ: "Bonaire, Sint Eustatius and Saba",
	BR: "Brazil",
	BB: "Barbados",
	BN: "Brunei",
	BT: "Bhutan",
	BV: "Bouvet Island",
	BW: "Botswana",
	CF: "Central African Republic",
	CA: "Canada",
	CC: "Territory of the Cocos (Keeling) Islands",
	CH: "Switzerland",
	CL: "Chile",
	CN: "China",
	CI: "Ivory Coast",
	CM: "Cameroon",
	CD: "Congo",
	CG: "Congo Republic",
	CK: "Cook Islands",
	CO: "Colombia",
	KM: "Comoros",
	CV: "Cabo Verde",
	CR: "Costa Rica",
	CU: "Cuba",
	CW: "Curaçao",
	CX: "Territory of Christmas Island",
	KY: "Cayman Islands",
	CY: "Cyprus",
	CZ: "Czechia",
	DE: "Germany",
	DJ: "Djibouti",
	DM: "Dominica",
	DK: "Denmark",
	DO: "Dominican Republic",
	DZ: "Algeria",
	EC: "Ecuador",
	EG: "Egypt",
	ER: "Eritrea",
	EH: "Sahrawi Arab Democratic Republic",
	ES: "Spain",
	EE: "Estonia",
	ET: "Ethiopia",
	FI: "Finland",
	FJ: "Fiji",
	FK: "Falkland Islands",
	FR: "France",
	FO: "Faroe Islands",
	FM: "Federated States of Micronesia",
	GA: "Gabon",
	GB: "United Kingdom",
	GE: "Georgia",
	GG: "Bailiwick of Guernsey",
	GH: "Ghana",
	GI: "Gibraltar",
	GN: "Guinea",
	GP: "Guadeloupe",
	GM: "Gambia",
	GW: "Guinea-Bissau",
	GQ: "Equatorial Guinea",
	GR: "Greece",
	GD: "Grenada",
	GL: "Greenland",
	GT: "Guatemala",
	GF: "Guiana",
	GU: "Guam",
	GY: "Guyana",
	HK: "Hong Kong",
	HM: "Heard Island and McDonald Islands",
	HN: "Honduras",
	HR: "Croatia",
	HT: "Haiti",
	HU: "Hungary",
	ID: "Indonesia",
	IM: "Isle of Man",
	IN: "India",
	IO: "British Indian Ocean Territory",
	IE: "Ireland",
	IR: "Iran",
	IQ: "Iraq",
	IS: "Iceland",
	IL: "Israel",
	IT: "Italy",
	JM: "Jamaica",
	JE: "Jersey",
	JO: "Hashemite Kingdom of Jordan",
	JP: "Japan",
	KZ: "Kazakhstan",
	KE: "Kenya",
	KG: "Kyrgyzstan",
	KH: "Cambodia",
	KI: "Independent and Sovereign  Kiribati",
	KN: "St Kitts and Nevis",
	KR: "South Korea",
	XK: "Kosovo",
	KW: "Kuwait",
	LA: "Laos",
	LB: "Lebanon",
	LR: "Liberia",
	LY: "Libya",
	LC: "Saint Lucia",
	LI: "Liechtenstein",
	LK: "Sri Lanka",
	LS: "Lesotho",
	LT: "Republic of Lithuania",
	LU: "Luxembourg",
	LV: "Latvia",
	MO: "Macao",
	MF: "Saint Martin",
	MA: "Morocco",
	MC: "Monaco",
	MD: "Republic of Moldova",
	MG: "Madagascar",
	MV: "the Maldives",
	MX: "Mexico",
	MH: "the Marshall Islands",
	MK: "North Macedonia",
	ML: "Mali",
	MT: "Malta",
	MM: "Myanmar",
	ME: "Montenegro",
	MN: "Mongolia",
	MP: "Northern Mariana Islands",
	MZ: "Mozambique",
	MR: "Mauritania",
	MS: "Montserrat",
	MQ: "Martinique",
	MU: "Mauritius",
	MW: "Malawi",
	MY: "Malaysia",
	YT: "Mayotte",
	NA: "Namibia",
	NC: "New Caledonia",
	NE: "Niger",
	NF: "Territory of Norfolk Island",
	NG: "Nigeria",
	NI: "Nicaragua",
	NU: "Niue",
	NL: "Netherlands",
	NO: "Norway",
	NP: "Nepal",
	NR: "Nauru",
	NZ: "New Zealand",
	OM: "Oman",
	PK: "Pakistan",
	PA: "Panama",
	PN: "Pitcairn Group of Islands",
	PE: "Peru",
	PH: "Philippines",
	PW: "Palau",
	PG: "Papua New Guinea",
	PL: "Poland",
	PR: "Puerto Rico",
	KP: "Democratic People's  Korea",
	PT: "Portugal",
	PY: "Paraguay",
	PS: "Palestine",
	PF: "French Polynesia",
	QA: "Qatar",
	RE: "Réunion",
	RO: "Romania",
	RU: "Russia",
	RW: "Rwanda",
	SA: "Saudi Arabia",
	SD: "Sudan",
	SN: "Senegal",
	SG: "Singapore",
	GS: "Georgia",
	SJ: "Svalbard og Jan Mayen",
	SB: "Solomon Islands",
	SL: "Sierra Leone",
	SV: "El Salvador",
	SM: "San Marino",
	SO: "Somalia",
	PM: "Saint Pierre and Miquelon",
	RS: "Serbia",
	SS: "South Sudan",
	ST: "Democratic  São Tomé and Príncipe",
	SR: "Suriname",
	SK: "Slovakia",
	SI: "Slovenia",
	SE: "Sweden",
	SZ: "Eswatini",
	SX: "Sint Maarten",
	SC: "Seychelles",
	SY: "Syria",
	TC: "Turks and Caicos Islands",
	TD: "Chad",
	TG: "Togo",
	TH: "Thailand",
	TJ: "Tajikistan",
	TK: "Tokelau",
	TM: "Turkmenistan",
	TL: "East Timor",
	TO: "Tonga",
	TT: "Trinidad and Tobago",
	TN: "Tunisia",
	TR: "Turkey",
	TV: "Tuvalu",
	TW: "Taiwan",
	TZ: "Tanzania",
	UG: "Uganda",
	UA: "Ukraine",
	UM: "U.S. Minor Outlying Islands",
	UY: "Uruguay",
	US: "United States",
	UZ: "Uzbekistan",
	VA: "Vatican City",
	VC: "Saint Vincent and the Grenadines",
	VE: "Venezuela",
	VG: "Virgin Islands",
	VI: "U.S. Virgin Islands",
	VN: "Vietnam",
	VU: "Vanuatu",
	WF: "Territory of the Wallis and Futuna Islands",
	WS: "Independent Samoa",
	YE: "Yemen",
	ZA: "South Africa",
	ZM: "Zambia",
	ZW: "Zimbabwe",
};

const countries = invert(countriesShort);
export { countries };
